language: node_js
node_js:
  - "stable"

env:
  global:
    - CC_TEST_REPORTER_ID=d888f575ac49f6dc0b6b76da131e91335ffb4c8b725b899e61f814b19e3d0ccb

cache:
  directories:
    - "node_modules"

services:
  - postgresql

before-script:  
  - psql -c "create database hims_project;" -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'root';" -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:  
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
